### ISSUE TITLE
Events don't fire in phpunit. How do I make them fire?

### ISSUE THREAD

**Issue by rickmacgillis** [cybercog/laravel-ban#34] opened 2018-09-26 21:52 UTC
So, I've been struck trying to figure out why the events don't fire for Laravel Ban in PHPUnit, but they function just fine when running the code in the browser.

Is there something special that I need to do to test for events in packages and make them fire?

Just an FYI, I ran the Laravel Ban tests and those pass without issue. The code I wrote for my project works just the same as in those tests and in the docs. (Albeit going through application specific code) So, it functions just fine when the browser-based version runs over the LOC that the tests are running.

I've tested to see if PHPUnit runs the service provider to observe the `Ban` model in the first place, and it runs that code. I've even manually added the code to observe the model, directly into the test as the first line of code, and that doesn't work. I've also removed all mocking from the tests to allow every event to fire, but the observer doesn't fire, and so the code that checks if a model got banned by the observer setting it in the DB properly, fails the check. It just doesn't fire.

Something is vehemently trying to make it NOT fire, and I need to know why. I have a hunch that it has to do with the way the code is bootstrapped.

Here are my tests:

```
/**
	 * @group current
	 */
	public function testCanSuspendUser()
	{
		$this->expectsEvents(ModelWasBanned::class);
		
		$user = factory(User::class)->create();
		$this->assertFalse($user->isBanned());
		
		$user->ban([
			'comment'		=> 'blah',
			'expired_at'	=> null,
		]);
		
		$this->assertTrue($user->isBanned());
	}
	
	/**
	 * @group current
	 */
	public function testCanUnsuspendUser()
	{
		$this->expectsEvents(ModelWasUnbanned::class);
		
		$user = factory(User::class)->create();
		$user->ban();
		
		$user->unban();
		
		$this->assertFalse($user->isBanned());
	}
```

**Comment by rickmacgillis** [comment] 2018-09-26 22:27
@antonkomarev Try them as tests on the main Laravel app, as that's where I'm running mine from.

**Comment by antonkomarev** [comment] 2018-09-27 00:28
@rickmacgillis I see whats the problem.
Don't try to cover many cases within one test. It's good when your test cover only one thing at a time.
```php
/** @test */
public function test_it_can_fire_model_was_banned_event_on_user_ban()
{
    $this->expectsEvents(ModelWasBanned::class);

    $user = factory(User::class)->create();

    $user->ban([
        'comment' => 'blah',
        'expired_at' => null,
    ]);
}

/** @test */
public function it_can_ban_user()
{
    $user = factory(User::class)->create();
    $this->assertFalse($user->fresh()->isBanned());

    $user->ban([
        'comment' => 'blah',
        'expired_at' => null,
    ]);

    $this->assertTrue($user->fresh()->isBanned());
}
```

Your issue was in line where you are trying to assert that user is banned. You are calling it on model created from factory. It wouldn't have changes made in Observers.

**Comment by antonkomarev** [comment] 2018-09-27 00:30
Additionally I recommend to make factory state which will create not banned user.

This construction:
```php
$user = factory(User::class)->create();
$this->assertFalse($user->fresh()->isBanned());
```

Will be replaced with
```php
$user = factory(User::class)->states('not-banned')->create();
```
Call it whatever you like. It's just an example.

**Comment by antonkomarev** [comment] 2018-09-27 00:34
I'm closing this issue since it's not a bug. Feel free to continue conversation here if you still have any questions.

**Closed by antonkomarev** 2018-09-27 00:34 UTC
Labels: question

**Comment by antonkomarev** [comment] 2018-09-27 12:06
Code blocks I've provided were successfully tested in my application. I've tried yours and they are working too.

No need to get fresh instance of the model right after its creation. This `fresh()` call is useless.
```php
$user = factory(User::class)->states('not-banned')->create()->fresh();
```

You need to get fresh instance after suspend action.
```php
public function testCanSuspendUser()
{
    $user = factory(User::class)->states('not-banned')->create();

    repo('User')->suspend($user, "Test suspension");

    $this->assertTrue($user->fresh()->isBanned());
}
```

Or when you have to do many checks on the fresh instance you could call `refresh()` method.
```php
public function testCanSuspendUser()
{
    $user = factory(User::class)->states('not-banned')->create();

    repo('User')->suspend($user, "Test suspension");

    $user->refresh();
    $this->assertTrue($user->isBanned());
    $this->assertNotEmpty($user->bans);
}
```

I don't know why your events are not firing. What's written in test output, it usually gives you a vision what exactly failed. It should write something like:
> These expected events were not fired: [Cog\Laravel\Ban\Events\ModelWasBanned]

**Comment by antonkomarev** [comment] 2018-09-27 21:01
@rickmacgillis from the source code.

`fresh()` method will refetch model and its loaded relations from database and return it.
```php
$freshUser = $user->fresh();
// $freshUser will have fresh instance, and $user wouldn't be modified
```
Using this way `$user` will be immutable and your fresh model will be assigned to new variable.

`refresh()` method will refetch model and its loaded relations from database and reassign all the attributes and relations. Under the hood it will use `fresh()` method, but additionally will reassign all the attributes and relations.
```php
$user->refresh();
// $user will have fresh instance
```

**Comment by rickmacgillis** [comment] 2018-09-28 03:09
@antonkomarev No need. I just enjoyed the banter with someone who can keep up. :) It's not every day I meet someone else who's a high level software engineer.

With the tests failing only on my end then it must be something I need to work out locally when I come off of vacation. (I was working all day every day for weeks on this project, so I'm burned out!)

Thanks for your help.

**Comment by antonkomarev** [comment] 2018-10-04 21:36
@rickmacgillis Laravel documentation was updated with `fresh` & `refresh` methods.
You can find it in [Retrieving Models section](https://laravel.com/docs/5.7/eloquent#retrieving-models).

**Comment by rickmacgillis** [comment] 2018-10-04 22:13
Thank you.
